"""Add poster_url to Movie

Revision ID: 66592e585d75
Revises: c520cec656b0
Create Date: 2025-06-25 18:06:18.090033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66592e585d75'
down_revision = 'c520cec656b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('poster_url')

    # ### end Alembic commands ###
